# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_remove_article_categorie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categories',
        ),
    ]
