# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20161129_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('date_pub', models.DateField(verbose_name='date published')),
                ('categories', models.CharField(max_length=50)),
                ('abstract', models.CharField(max_length=1000)),
                ('keyword', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=1000)),
                ('categorie', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='article.categories')),
            ],
        ),
    ]
