# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20161129_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='id',
            new_name='id_pk',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='id',
            new_name='id_pk',
        ),
    ]
