# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_auto_20161129_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.categories'),
        ),
    ]
