# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_auto_20161129_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cat',
        ),
    ]
