# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0027_article_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='add_date',
            field=models.DateField(default='0', verbose_name='add_date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='writer',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
