# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0028_auto_20161205_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2016, 12, 5, 15, 43, 51, 740550), verbose_name='add_date'),
        ),
    ]
