# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 14:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0029_auto_20161205_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2016, 12, 5, 14, 46, 4, 241658, tzinfo=utc), verbose_name='add_date'),
        ),
    ]
