# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0037_article_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='writer',
            field=models.IntegerField(default=0),
        ),
    ]
