# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0038_article_writer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article',
            new_name='articles',
        ),
    ]
