# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0041_auto_20161207_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='categories',
        ),
        migrations.DeleteModel(
            name='articles',
        ),
    ]
