# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0042_auto_20161207_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='auth',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
